name: 'Ember Asset Size'
description: 'Find out how much of a change to your asset size a PR will have'
author: 'Chris Manson'
branding:
  icon: 'bar-chart-2'
  color: 'orange'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  show-total-size-diff:
    description: 'Display a table of the total differences in size for JS & CSS'
    required: false
    default: 'no'
  update-comments:
    description: 'Update existing asset size comment instead of creating a new one each time'
    required: false
    default: 'yes'
runs:
  using: 'node16'
  main: 'index.js'
